export const SET_CATEGORY_MED = 'SET_CATEGORY_MED';
export const SET_CATEGORY_DONOR = 'SET_CATEGORY_DONOR';
export const RESET_CATEGORY = 'RESET_CATEGORY';

export const LOGGING_IN = 'LOGGING_IN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGGING_OUT = 'LOGGING_OUT';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const REGISTRATION_PROCESSING = 'REGISTRATION_PROCESSING';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';