export const SET_CATEGORY_MED = 'SET_CATEGORY_MED';
export const SET_CATEGORY_DONOR = 'SET_CATEGORY_DONOR';
export const RESET_CATEGORY = 'RESET_CATEGORY';

export const LOGGING_IN = 'LOGGING_IN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGGING_OUT = 'LOGGING_OUT';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const REGISTRATION_PROCESSING = 'REGISTRATION_PROCESSING';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';

export const FETCHING_DONORS = 'FETCHING_DONORS';
export const DONORS_FETCHED = 'DONORS_FETCHED';
export const DONORS_FAILED = 'DONORS_FAILED';
export const DONORS_RESET = 'DONORS_RESET';


export const FETCHING_INBOX = 'FETCHING_DONORS';
export const INBOX_FETCHED = 'INBOX_FETCHED';
export const INBOX_FAILED = 'INBOX_FAILED';
export const FETCHING_REQUESTS = 'FETCHING_REQUESTS';
export const REQUESTS_FETCHED = 'REQUESTS_FETCHED';
export const REQUESTS_FAILED = 'REQUESTS_FAILED';
export const REQUESTS_RESET = 'REQUESTS_RESET';

export const FETCHING_REQINFO = 'FETCHING_REQINFO';
export const REQINFO_FETCHED = 'REQINFO_FETCHED';
export const REQINFO_FAILED = 'REQINFO_FAILED';
export const REQINFO_RESET = 'REQINFO_RESET';
